project:
  type: website
  output-dir: docs

website:
  title: "Introduction into bioinformatics tools"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sanger.qmd
      - alignment.qmd
      - phylogenetics.qmd
      - qPCR_presentation.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



